mount read buffer folders into assistant Docker containers

diff --git a/seamless-cli/seamless-delegate b/seamless-cli/seamless-delegate
--- a/seamless-cli/seamless-delegate
+++ b/seamless-cli/seamless-delegate
@@ -44,13 +44,16 @@ fi
 if [[ $assistant == none ]] ; then
   assistant=''
 fi
+if [ -z "$SEAMLESS_READ_BUFFER_FOLDERS" ]; then
+    SEAMLESS_READ_BUFFER_FOLDERS=""
+fi
 set -u
-
-export READ_BUFFER_FOLDER_1=$(python -c 'import os, sys; inp=sys.argv[1].split(";"); print(os.path.abspath(inp[0]) if len(inp) > 0 else "")' $SEAMLESS_READ_BUFFER_FOLDERS)
-export READ_BUFFER_FOLDER_2=$(python -c 'import os, sys; inp=sys.argv[1].split(";"); print(os.path.abspath(inp[1]) if len(inp) > 1 else "")' $SEAMLESS_READ_BUFFER_FOLDERS)
-export READ_BUFFER_FOLDER_3=$(python -c 'import os, sys; inp=sys.argv[1].split(";"); print(os.path.abspath(inp[2]) if len(inp) > 2 else "")' $SEAMLESS_READ_BUFFER_FOLDERS)
-export READ_BUFFER_FOLDER_4=$(python -c 'import os, sys; inp=sys.argv[1].split(";"); print(os.path.abspath(inp[3]) if len(inp) > 3 else "")' $SEAMLESS_READ_BUFFER_FOLDERS)
-export READ_BUFFER_FOLDER_5=$(python -c 'import os, sys; inp=sys.argv[1].split(";"); print(os.path.abspath(inp[4]) if len(inp) > 4 else "")' $SEAMLESS_READ_BUFFER_FOLDERS)
+python -c 'import os, sys; inp=sys.argv[1].split(";"); _= exit(1) if len(inp) > 5 else None' $SEAMLESS_READ_BUFFER_FOLDERS "" || (echo 'SEAMLESS_READ_BUFFER_FOLDERS contains more than 5 folders, this cannot be mapped into the assistant Docker container'; exit 1)
+export READ_BUFFER_FOLDER_1=$(python -c 'import os, sys; inp=sys.argv[1].split(";"); print(os.path.abspath(inp[0]) if len(inp) > 0 else "")' $SEAMLESS_READ_BUFFER_FOLDERS "")
+export READ_BUFFER_FOLDER_2=$(python -c 'import os, sys; inp=sys.argv[1].split(";"); print(os.path.abspath(inp[1]) if len(inp) > 1 else "")' $SEAMLESS_READ_BUFFER_FOLDERS "")
+export READ_BUFFER_FOLDER_3=$(python -c 'import os, sys; inp=sys.argv[1].split(";"); print(os.path.abspath(inp[2]) if len(inp) > 2 else "")' $SEAMLESS_READ_BUFFER_FOLDERS "")
+export READ_BUFFER_FOLDER_4=$(python -c 'import os, sys; inp=sys.argv[1].split(";"); print(os.path.abspath(inp[3]) if len(inp) > 3 else "")' $SEAMLESS_READ_BUFFER_FOLDERS "")
+export READ_BUFFER_FOLDER_5=$(python -c 'import os, sys; inp=sys.argv[1].split(";"); print(os.path.abspath(inp[4]) if len(inp) > 4 else "")' $SEAMLESS_READ_BUFFER_FOLDERS "")
 
 currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`
 cd $currdir
